version: '3'

services:
  mysqldev:
    image: mysql:5.7
    volumes:
      - C:\Users\pheli\Documents\Phelipe\Projetos:/mysql/mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      TZ: America/Sao_Paulo
    ports:
      - 13306:3306